### ISSUE TITLE
Setup Frontend with Next.js

### ISSUE THREAD

**Issue by bjupreti** [bjupreti/karyakram-frontend#1]

**Comment by bjupreti** [comment]
Thinking of setting up the project with Next.js as I have worked with React before but if the contributor thinks there is something more exciting and they will be able to help then we might consider using it as well.

**Comment by NavGithub15** [comment]
Initial setup for the project is finished. Next.js with Typescript and Tailwind CSS for styling.

**Comment by NavGithub15** [comment]
Initial setup for the project is finished. Next.js with Typescript and Tailwind CSS for styling.

**Comment by AbhijeetShk** [comment]
What is needed to be done now?

**Comment by NavGithub15** [comment]
Nothing needs to be done now. Initial setup is done.
