### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by bjupreti** [bjupreti/karyakram-frontend#5]
Now we have default README from Next.js. We need to update our readme as per our project requirements.

**Comment by NavGithub15** [comment]
Hi Bijay. I would like to contribute to on this issue. Can you please assign this issue to me?

**Comment by bjupreti** [comment]
Hey @NavGithub15, sounds good! I have assigned this issue to you.

**Comment by NavGithub15** [comment]
I have created a pull request #6 for updating readme file

**Comment by bjupreti** [comment]
Fixed by https://github.com/bjupreti/karyakram-frontend/pull/6
